### ISSUE TITLE
How to use only the snapshot function to an application?

### ISSUE THREAD

**Issue by Ljandler** [robmikh/Win32CaptureSample#15]
Hello, I want to create an application in C ++
that captures a snapshot of the game screen at each interval.
This example was the only one that worked in games.
Only with the game's HWND does it create a snapshot of the game, even if the game window is inactive.
My problem is that I am not able to extract just the piece of code that creates the snapshots.
Would you help me?
I just wanted an example of how to create a snapshot of a game's HWND.
To then analyze snapshot.png with OpenCV.

**Comment by robmikh** [comment]
You should be able to consume the capture API through any projection or using the ABI directly. I'd recommend using C++/WinRT like in this sample. You'll have to add that to your project through nuget and make sure you have the proper WindowsSDK installed.

After that, you may want to take a peek at this repo: https://github.com/robmikh/ScreenshotFun
That sample captures the primary monitor, crops it using some d2d geometry, and then saves it to a file.

You'll want to modify it in this way:
- Instead of finding the primary monitor, find the HWND that represents the game window and call CreateCaptureItemForWindow.
- You can ignore everything after the "// Get a D2D bitmap for our snapshot" comment. You can also ignore the parts about the filer picker. The `frameTexture` variable will contain the d3d texture with the game in it.
- It's been awhile since I've used OpenCV, so I'm unsure if there are helpers to allow it to take in ID3D11Texture2D objects. If there isn't, you'll want to modify `CaptureSnapshot.cpp` and change a few of the flags:

  - Change the `Usage` field to `D3D11_USAGE_STAGING `
  - Change the `BindFlags` field to `0`
  - Change the `CPUAccessFlags` field to `D3D11_CPU_ACCESS_READ`

   That should give you a texture that you can call the [Map](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-map) API with to get the bits from the texture. Don't forget to call Unmap when you're done!

That should give you a running start.

**Comment by Ljandler** [comment]
Thanks, I got what I wanted!
