### ISSUE TITLE
HWND Capture returns empty texture if using CreateFreeThreaded.

### ISSUE THREAD

**Issue by MartinClementson** [robmikh/Win32CaptureSample#16]
Hi. Thank you for such a helpful sample project.

I am building a dll that provides functionality to capture monitor and HWND output (It's similar to the SimpleCapture class in the sample). It's was working well until I decided to switch to using "CreateFreeThreaded" due to the project using the dll having the UI on the main thread. For some reason, the HWND capture stops working when it's not run on the main thread. I receive a new texture in the callback function, but all the pixels have the value 0.

I tried doing the same on the Win32CaptureSample by changing to CreateFreeThreaded. It works on the sample project. The difference in my dll project is that instead of outputting to the back buffer, I copy the texture to a staging texture. It does not fail anywhere, but maybe it has something to do with it when running on a worker thread?

Is there anything I need to consider when grabbing from HWND on a worker thread?

Thanks
Martin

**Comment by MartinClementson** [comment]
Update: I realized that this does not apply to all HWND as I started to test more.


The ones working have either class name starting with "hwndWrapper" or "Chrome_widgetWin_x" (x = 0,1,etc) (Although this can differ from app to app whether it works or nor)

app [ClassName]
**Tested apps that are not working:**
- Chrome [Chrome_widgetWin_1]
- Calculator [ApplicationFrameWindow]
- Snipping tool [Microsoft-Windows-SnipperEditor]
- Notepad++ [NotePad++]
- Task Manager [TaskManagerWindow]

**Tested apps that are working**
- Microsoft Teams [Chrome_widgetWin_1]
- Spotify  [Chrome_widgetWin_0]
- SourceTree [HwndWrapper]
- Visual Studio [HwndWrapper]


This seems to have something to do with access to those HWND which is beyond my knowledge of the system.

**Comment by robmikh** [comment]
I'm glad you find the sample useful! 🙂 

> I tried doing the same on the Win32CaptureSample by changing to CreateFreeThreaded. It works on the sample project.

This heavily suggests to me that something is going on with how you're making the copy/handling synchronization. For background, CreateFreeThreaded changes the marshaling behavior of the callback but has no impact on the rendering. In fact, the DWM has no knowledge of this part of the capture API. Rendering is done in the DWM process and the buffer is sent back to the capturing application.

Additionally, using CreateFreeThreaded will cause the FrameArrived event to call you back on the frame pool's internal worker thread. Is your pipeline set up to account for things coming from a different thread?

What is the threading situation like for your application in regards to your usage of D3D? One thing I would try is to use the [ID3D11Multithread](https://docs.microsoft.com/en-us/windows/win32/api/d3d11_4/nn-d3d11_4-id3d11multithread) interface to lock the device when you're doing operations with it or the device context. 

Finally, if you'd like to use Create instead of CreateFreeThreaded, you can do this on a thread other than the main thread. You just have to have a DispatcherQueueController on that thread and make sure you're pumping messages. You can do this by creating a controller for your thread and pumping messages manually, or [creating a dedicated thread with the controller ](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuecontroller.createondedicatedthread?view=winrt-19041#Windows_System_DispatcherQueueController_CreateOnDedicatedThread)(which will pump messages for you). This may not be right for your scenario, but I thought I'd mention it.

If you can put together a simplified repro project, I'd be happy to take a look. Additionally, what build of Windows are you encountering this problem on?

**Comment by MartinClementson** [comment]
Thank you for that answer Robert, that was helpful.

I tried using the ID3D11Multithread interface, but it didn't solve it for me and introduced another issue. So I opted for your suggestion at the end of your reply, and it worked well. ( I'll post some code below how I did it in case anyone finds this thread in search of some help).

Regarding the DWM process, Is there any way to modify the rate at which the DWM is rendering the image? The DWM process is using a significant amount of GPU power when running on my machine and it would be great if it could limit it to a target framerate.


**How I set up the DispatcherQueue**

namespace abi = ABI::Windows::System;
DispatcherQueueOptions options
{
    sizeof(DispatcherQueueOptions),
    DQTYPE_THREAD_DEDICATED,
    DQTAT_COM_STA
};

HRESULT disControlOK = CreateDispatcherQueueController(options, reinterpret_cast<abi::IDispatcherQueueController**>(winrt::put_abi(m_controller)));

if (FAILED(disControlOK)) 
       //Could not create Controller  

 m_DispatchQueue = m_controller.DispatcherQueue();

//Calling functions on the worker thread
winrt::DispatcherQueueHandler handler =[](){ /* Any code to run on the worker thread here*/};
bool isQueued = m_DispatchQueue.TryEnqueue(winrt::DispatcherQueuePriority::High, handler);
if(isQueued)
    //Success

**Comment by robmikh** [comment]
The DWM will render a new frame if a buffer is available. This means you can control the rendering by controlling the lifetimes of the `Direct3D11CaptureFrame` objects. 

For example, if you have a frame pool with 2 buffers, you can stop the DWM from rendering by holding onto two Direct3D11CaptureFrame objects (don't release or dispose/close them). Releasing a frame will make it available to the DWM again.

We've had clients who make their frame pool 1 buffer to make that control easier.

Just out of curiosity, what's the CPU/GPU on the machine you're running this on? Using capture will increase GPU usage (we are doing rendering work, after all), but it shouldn't be too bad. We've mainly run into issues with virtual machines that only have 1 CPU core and are running on [WARP](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp) (aka the software adapter).

**Comment by MartinClementson** [comment]
That makes sense, and it worked like a charm. I wanted a way to throttle the GPU usage of the DMW to help slower or already busy GPU's, and essentially control the frame rate so that it does not render frames unnecessarily for apps that might need the textures at a different framerate. (In my case I am streaming textures over the network at user-defined framerate between 25 -60 fps, while the app performing the capture is running at 60).

I don't think the GPU usage is out of the ordinary, I realized that the DWM is capturing on the integrated GPU rather than the NVIDIA GPU. I haven't found a way to change the GPU the DWM is using,  it could just be how it is on dual GPU laptops, it seems to me that it's not too uncommon to have these issues on this kind of setup. (The older Desktop Duplication API was rather tricky to program for dual GPU laptop setups).

My setup is 
Razer Blade 15 Laptop
CPU:    Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
GPU0:  Intel(R) UHD Graphics 630
GPU1:  NVIDIA GeForce GTX 1660 Ti
