### ISSUE TITLE
How to enable isWin32ProgrammaticPresent for capturing without capturePicker?

### ISSUE THREAD

**Issue by BillWCJ** [robmikh/Win32CaptureSample#33]
Hi, 

Just want to start off by saying that this sample is really great and really helped me get started with the API! Thanks you so much!

### Background

I am a bit new to the area and this might be a dumb question.

I was stuck trying to use App::StartCapture(HWND) and App::StartCapture(HMONITOR) to start programmatic capturing without using the graphics picker. The error I keep getting was "Interface Not Support" while creating the capture item and was stuck for a few month :( I also made some mistakes detailed later.

I gave up and started testing using the capturePicker, that had no problems. But I really wanted create captureItems without using the the pop up window of capture picker. 

I found some confusing/conflicting info online elsewhere and want to just clarify.

I am using the latest Windows SDK 10.0.19041.0 and it seems that I only still have Version 7 of L"Windows.Foundation.UniversalApiContract". I should have saw this and realized my mistakes...

```
    auto isWin32ProgrammaticPresent = winrt::ApiInformation::IsApiContractPresent(L"Windows.Foundation.UniversalApiContract", 8);
```

### Question
Is Win32Programmatic capturing actually supported today? (i.e. I should be able to use App::StartCapture(HWND) and not limited to use capturePicker)

If so: 
what could I be doing wrong and where should I look?

If not:
Was it supported in the past and got removed?
Will it be supported in the future? If not, maybe the deprecated code should be removed to avoid confusion?

Thank you in advance!

**Comment by robmikh** [comment]
I'm glad you've found the sample useful!

Something to keep in mind is that while you may be using the newest version of the SDK, you still have to run your program on a build of Windows that supports those features. The SDK only contains headers and metadata for the capture API (and other Windows APIs) but it does not contain the implementation. The implementation is shipped with the operating system, and you have to be on the right version to get those features.

When the sample calls `ApiInformation::IsApiContractPresent` at runtime, it's querying the metadata found on your local machine (usually something like `C:\Windows\System32\WinMetadata`). This provides the information of what is and is not available on that machine. As you've noted, your program might have knowledge of a particular interface, but if the system doesn't implement it you won't be able to use it.

I would suggest updating your build, and then you should have access to programmatically capture the screen. If your machine is reporting contract version 7, you're likely on build 17763 (also known as 1809, because why not). It looks like we have actually stopped servicing that build last November according to [MSDN](https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1809-end-of-servicing). You may want to consider upgrading regardless.

**Comment by BillWCJ** [comment]
OH MY GOD... that was my problem all along...

Thank you sooo much Robert! Thank you so much for the fast response and thank you so much for the explanation to help me understand. I should've asked long ago.

Thanks again!
