### ISSUE TITLE
Graphics Capture limits DXGI Desktop Duplication update frequency

### ISSUE THREAD

**Issue by elvissteinjr** [robmikh/Win32CaptureSample#34]
Hi, it's me again. Hope this place is still good for reporting general Graphics Capture issues, as this once again isn't on the sample app itself.

My app supports both Desktop Duplication and Graphics Capture. With Desktop Duplication being able to report cursor updates instantly (1000 Hz mouse setting actually delivers 1000 updates per second) and working with exclusive fullscreen applications (on some APIs/games even at frame rates beyond the display's they're rendered to), it still has its use. As my application runs in VR with headsets having higher refresh rates than the still typical bog standard 60 Hz display, those extra frames contribute to a smoother output on that end.

I only recently noticed this, but it appears that using Graphics Capture does impose limits on Desktop Duplication updates. It doesn't matter which application is using Graphics Capture. Starting a capture from the sample affects my app for example. Once this happens, the maximum update rate seems to drop to whatever the primary display's refresh rate is.

I know this isn't exactly critical but I'm still slightly bummed about this side-effect. In any case I wanted to put it out there at least.

In case this depends on the setup, I'm currently running Windows 10 20H2 with an Nvidia card.
Don't have a test app for desktop at hand (for SteamVR, [Desktop+](https://github.com/elvissteinjr/DesktopPlus) can show this behavior), but I suppose adding a frame counter to the DXGI Desktop Duplication Sample would do the trick, so I could do that if wanted.

I apologize if this one's out of place here, but it seems to be caused by Graphics Capture and I've had good experiences by actually getting responses here before so yeah, thanks!

**Comment by robmikh** [comment]
Hello again! 🙂 Yes, this is still a fine place to ask questions/report issues. Once I get something more official set up I'll start redirecting folks.

So when the Desktop Duplication API (DDA) is targeting a monitor that the compositor has ownership of, we (we being the system compositor) are responsible for rendering frames. When a game goes true exclusive full screen, we're out of the picture and shouldn't be able to effect DDA. I'm guessing you're seeing this behavior in the non-exclusive full screen case?

One potential source of the problem is that Windows.Graphics.Capture currently forces the software cursor on, which has side-effects on the system. This can also cause some games that use the system cursor instead of drawing their own to get booted out of overlay code-paths, forcing the compositor to compose at the primary monitor's refresh rate. This is something we're working on fixing, but it requires larger changes to the OS that we're also still working on.

Do the actual frames get throttled to the refresh rate of the primary monitor, or are you getting fewer cursor updates? One way to reproduce the software cursor behavior without using WGC is to turn on cursor trails in the mouse settings. If you turn that on, do you see the same issue?

**Comment by elvissteinjr** [comment]
I may have indeed jumped the gun a bit here. After double-checking it seems to indeed only affect cursor updates. Unconstrained frame rate duplication still works in the few instances they do.
I suppose I could poll the mouse coordinates in these cases if I really wanted (cursor is separate in DDA anyways after all), making this even more of a non-issue. Cursor movement was just the easiest to check and the most apparent case. And yep, having cursor trails enabled has the same effect as it turns out. Sorry about that.

Whether it's truly true exclusive fullscreen I'm looking at here or not... I honestly don't know. That stuff is a bit muddy these days, isn't it? So far I've only been able to have DDA give me higher frame rates than what the duplicated monitor is set at from OpenGL and Vulkan applications with vsync off set to non-windowed fullscreen... but even that doesn't work on everything that fits the pattern. Graphics Capture doesn't work on those though, so they're probably exclusive.
But since it turns out that case still works, doesn't matter much I suppose.

Always interesting to hear of some internal details, though. Actually, would the software cursor still be required if the cursor is disabled for the Capture? I happen to hide the cursor from the captures most of the time, so that'd be actually helpful in my case at least.

Anyways, sorry about that again. I'll try to be more careful next time.

**Comment by robmikh** [comment]
No worries! I'd rather you file something like this and we talk it through than have an issue go undetected. Someone else who has a similar problem might stumble across this issue in their search as well.

Unfortunately, no, disabling the cursor in the capture does not stop us from forcing the software cursor. I'm actually in the middle of a mitigation that would enable that, but it has its own issues/risks we're working through internally.

As for true exclusive full screen, you're correct. We emulate that mode to provide a better experience when switching between the game and the desktop environment, as well as enabling things like the Xbox Game Bar. I think most DX games end up in this mode, OpenGL and Vulkan games currently do not to the best of my knowledge. A quick test can be trying to bring up the Game Bar, if it doesn't show up (or you get an error), then the game is probably truly in exclusive full screen mode. If it is exclusive, the bits are out of reach of the system compositor, and we don't have access to them in Windows.Graphics.Capture.
