### ISSUE TITLE
Win10 18362 lock screen issue

### ISSUE THREAD

**Issue by Russellqiu** [robmikh/Win32CaptureSample#35]
Hello, I found that in the low version of Win10 lock screen will stop the screenshot, but in the high version of the system lock screen can be captured normally，how to take screenshots normally after locking the screen on 18362 verion?

**Comment by robmikh** [comment]
The lock screen isn't something that's currently supported by the API. You can sometimes capture it because of the way the visual tree works and when the DWM from your session is or isn't reused for the lock screen. For the time being, I'd recommend looking into [DDA](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api) or an [indirect display driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview) depending on your scenario. This may change for Windows.Graphics.Capture in the future, but no promises at this time.
