### ISSUE TITLE
Capture frame rate

### ISSUE THREAD

**Issue by visuall** [robmikh/Win32CaptureSample#36]
Hello ... this is more a question than issue ... is there any way to configure the frame rate at which the SDK will deliver frames? Right now ( testing on nvidia card ) it delivers frames at 60fps. I tried configuring the vsync of my card and decreased it in half but still the same. I do not want to drop samples on my own because this way quality may suffer especially given these are textures and there is no easy way to tell if the texture is unique or same as previous. Any idea if this can be done ?

**Comment by robmikh** [comment]
The API will return frames at most at the refresh rate of the primary monitor. But you may control this by manipulating the lifetime of the Direct3D11CaptureFrame. When you create your frame pool, you specify how many buffers it will hold. If all buffers are outstanding, that is, if you maintain a reference to all Direct3D11CaptureFrame objects that are provided by `TryGetNextFrame`, then the DWM will not draw a new frame since none are free.  At this time it's the only way to control the rate at which you get frames back from the API.

**Comment by visuall** [comment]
Thank you!
