### ISSUE TITLE
StartCapture and RPC errors

### ISSUE THREAD

**Issue by roman380** [robmikh/Win32CaptureSample#38]
I have a question, which I unfortunately can ask with partial detail. In certain specific scenarios (generally the API normally works reliably) I am seeing `IGraphicsCaptureSession::StartCapture` producing internal exception `RPC_S_SERVER_UNAVAILABLE` or `RPC_S_CALL_FAILED` and then the same HRESULT is returned from the API function call.

I wonder if you maybe have some comments about what could be causing this and maybe certain unobvious API limitations?

I am expecting this might be hitting something known since as I mentioned there is little additional info I can give. As far as I understand this does not happen with first session started, instead this problem comes up with recurring and/or concurrent sessions for the same graphics item. One another potential problem might be an unknown threading/apartment status os the caller, the calls could be made on weird threads.

**Comment by robmikh** [comment]
Unfortunately there's not much I can say without more information. Your best bet is to attempt to get a new GraphicsCaptureItem when you hit this issue, as the user service that backs the Capture API might have gone down either due to an error in our code or an error in other tenants of the same service process.
