### ISSUE TITLE
The procedure entry point CreateDispatcherQueueController could not located on Windows 10, version 1607

### ISSUE THREAD

**Issue by xluogithub** [robmikh/Win32CaptureSample#39]
Hi Team,
This Win32CaptureSample is a great example to learn and use Windows.Graphics.Capture API. It helps me to implement capturing other application window. Really appreciate you to create such great project.

Background
My desktop Windows application is using C++ and Windows APIs. And my app has been used by instructors in the classroom to collect votes from students. It's one functionality is to capture an image of other application window such as Power Point Slide or web browser window or Google slide... I have used Windows.Graphics.Capture APIs to implement this capture feature. It runs great on Windows10, version 19043. 
One requirement is that my app should run on all versions of Windows 10. I Know that Windows.Graphics.Capture is only supported on Windows 10, version 1803 or above. On Windows 10, version 1803 below, it would be ok to not provide this capturing functionality, but we do need to be able to run my app on Windows 10, version 1803.

Question
How to configure Win32CaptureSample project not load DLLs of Windows.Graphics.Capture APIs at runtime if the app detects that Windows OS's version is below Windows 10, version 1803?
I tried to test the Win32CaprtureSample project on Windows 10, version 1607 machine. First of all, I built the Win32CaptureSample without any errors on this machine win10 1607, but when I ran under MSVC2017/2019 IDE, I got the following error:|
The procedure entry point CreateDispatcherQueueController could not located.
How to resolve this runtime error?

Here I have attached two screenshots, one is my win10 version 1607, the other is error message.
Thanks for your help and looking forward to your solution on this,
<img width="810" alt="win10-version" src="https://user-images.githubusercontent.com/52013960/135761650-cb8a2270-1ba0-41a5-8b38-8a17f2e6fbec.png">
<img width="1021" alt="error_to_launch" src="https://user-images.githubusercontent.com/52013960/135761658-21373e14-36e2-4fce-a1b5-9adf7e587e93.png">

**Comment by robmikh** [comment]
I'm glad you find the sample useful!

There are two issues you'll need to resolve:

  * Check for the existence of Windows.Graphics.Capture at runtime
  * Delayload or dynamically load CoreMessaging.dll
  
You can check the existence of a WinRT API at runtime by using the [`ApiInformation`](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.ApiInformation?view=winrt-20348) API. Keep in mind that you'll at minimum will need to be running Windows 10 10.0.10240.0 (the first release) to call this API. As an example, here's how you could modify the check at the beginning of the Win32CaptureSample:

```cpp
auto isCaptureSupported = 
    winrt::ApiInformation::IsTypePresent(winrt::name_of<winrt::GraphicsCaptureSession>()) && 
    winrt::GraphicsCaptureSession::IsSupported();
```

Another thing you should keep in mind with the `ApiInformation` API is that is parses the metadata found on the user's machine, so I would refrain from constantly calling this API. I would cache this value per application session at the beginning.

The second issue is the one you're seeing, where the loader fails to find the appropriate export from CoreMessaging.dll. [`CreateDispatcherQueueController`](https://docs.microsoft.com/en-us/windows/win32/api/dispatcherqueue/nf-dispatcherqueue-createdispatcherqueuecontroller) was introduced in version 1709, and the export won't exist on older versions of Windows. You can resolve this by either [delayloading](https://docs.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls?view=msvc-160) CoreMessaging.dll, or manually calling LoadLibrary and GetProcAddress instead of linking directly.

I'm going to close this issue, but feel free to reply here if you have more questions about running down-level.

**Comment by xluogithub** [comment]
Thanks for your reply and provided a solution for solving the issues. Really appreciate!
Here are what I have done:
1. Once launching my app, will check Windows 10 build number. If OS build number >= 17763 (for Win10 version 1809), I will use/call Windows.Graphics.Capture's APIs.
2. In the linker option, I use Delayload CoreMessaging.dll with /DELAYLOAD:CoreMessaging.dll.
After making above changes, my app could run on all Windows10 versions. For Windows10 build 17763 or above, my app will call Windows.Graphics.Capture's API to capture an image of other application's window. For Windows 10 build below 17763, my app will Not call Windows.Graphics.Capture's API and will NOT have a functionality to capture an image of other application window.

Just wondering how to capture an image of other application window in Windows10, version lower than 1803. 
Is there some other Windows API to do a capture since Windows.Graphics.Capture does not exist on Win10 version lower than 1803?

**Comment by robmikh** [comment]
Prior to Windows.Graphics.Capture, your best option would be to use the Desktop Duplication API and then cut out the window you're interested in. You can get the rect using `DwmGetWindowAttribute` with `DWMWA_EXTENDED_FRAME_BOUNDS` and copy it out using `CopySubresourceRegion`. Don't forget to transform the rect from desktop-space to monitor-space!
