### ISSUE TITLE
Desktop Duplication / WGC Questions

### ISSUE THREAD

**Issue by ryan-weil** [robmikh/Win32CaptureSample#46]
Hi, I have a few questions that I'd like to post if you don't mind. I have been creating a streaming application that captures the desktop using Desktop Duplication, then encodes the texture with Media Foundation and sends the frames over the network. My questions are as follows

- Are there any performance benefits of WGC compared to Desktop Duplication?
- Can WGC capture games in fullscreen?
    - If so, can WGC capture games in fullscreen on another adapter than it was run from? I.e, if a game is run in fullscreen on a dedicated card on a laptop, and the capture application is run on the integrated GPU, will it work?
- A big problem I am dealing with currently is when I capture external monitor plugged into my laptop, the texture will be on the other adapter and there is not much that can be done to access it currently besides copying to normal memory first, which I would assume has a massive impact on performance. Is there any other way? I know D3D12 has a shared heap feature, but as far as I know neither Desktop Duplication nor WGC support D3D12. Can you shed more light on what to do here?

**Comment by robmikh** [comment]
Yeah, no problem!

In general, WGC and DDA will perform similarly for monitor capture. The main differences are in usage, where WGC allows you to specify the number of buffers. Going forward, WGC will be where our efforts will be in adding features, but we're not quite at parity yet with DDA on a few features. The first feature is the dirty rect information you can get through DDA. Another is the ability to capture the secure desktop (DDA requires that you run as the SYSTEM account in order to do this). The third is the ability for DDA to capture full screen games that take ownership of the monitor. If the DWM is out of the picture, we can't capture it with WGC. Most DX games should now run in eFSE (emulated full screen exclusive) mode, so WGC will work. But other games that use OpenGL or Vulkan likely are not part of eFSE, unless that's changed recently.

As for cross-adapter scenarios, we don't have a great solution here at the moment. DDA will insist that you capture using a device on the correct adapter, while WGC will allow the capture to happen but will spill the bits into system memory to do the copy when rendering. For the best performance, you will want to still capture using the same adapter that is being used for the scanout, and then share the captured buffer with a DX12 device to use cross-adapter features. Note that WGC currently does not work with D3D 11-on-12.

**Comment by ryan-weil** [comment]
> Yeah, no problem!
> 
> In general, WGC and DDA will perform similarly for monitor capture. The main differences are in usage, where WGC allows you to specify the number of buffers. Going forward, WGC will be where our efforts will be in adding features, but we're not quite at parity yet with DDA on a few features. The first feature is the dirty rect information you can get through DDA. Another is the ability to capture the secure desktop (DDA requires that you run as the SYSTEM account in order to do this). The third is the ability for DDA to capture full screen games that take ownership of the monitor. If the DWM is out of the picture, we can't capture it with WGC. Most DX games should now run in eFSE (emulated full screen exclusive) mode, so WGC will work. But other games that use OpenGL or Vulkan likely are not part of eFSE, unless that's changed recently.
> 
> As for cross-adapter scenarios, we don't have a great solution here at the moment. DDA will insist that you capture using a device on the correct adapter, while WGC will allow the capture to happen but will spill the bits into system memory to do the copy when rendering. For the best performance, you will want to still capture using the same adapter that is being used for the scanout, and then share the captured buffer with a DX12 device to use cross-adapter features. Note that WGC currently does not work with D3D 11-on-12.

Thank you so much for your reply, Robert!

For the last paragraph, could you clarify a bit what you meant by ```For the best performance, you will want to still capture using the same adapter that is being used for the scanout, and then share the captured buffer with a DX12 device to use cross-adapter features. Note that WGC currently does not work with D3D 11-on-12.``` ?

Do you mean that once you get the D3D11Texture texture, to copy it to a d3d12 device and then display through there? If that's what you meant, despite the copying to the device, would it still perform significantly better than going through system memory? And if D3D 11-on-12 is not compatible, how would this be achievable?

**Comment by robmikh** [comment]
You can interoperate D3D11 and D3D12 without using 11-on-12. You'll have to be careful to get the synchronization right, but it would look something like this:

1. Receive a `Direct3D11CaptureFrame` from the capture API (keep a reference to it!).
2. Extract the texture and QI for `IDXGIResource1`.
3. Call [`IDXGIResource1::CreateSharedHandle`](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgiresource1-createsharedhandle) to obtain a handle to the texture.
4. Call [`ID3D12Device::OpenSharedHandle`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-opensharedhandle) to open the texture with your D3D12 device.
5. Do whatever you need to do on D3D12. I recommend making a copy to process later, this should be as short as possible.
6. Signal a fence created on that same D3D12 device and use something like [`ID3D12Fence::SetEventOnCompletion`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-seteventoncompletion) to be notified when that work has completed.
7. Only when you're sure you're not using the ID3D12Resource anymore on the GPU, release all of the references to the texture and then finally call `Close` on your `Direct3D11CaptureFrame` from step 1.

You'll need to profile your implementation, but I would expect it to be faster than copying the bytes to system memory and then back to video memory.

**Comment by ryan-weil** [comment]
> You can interoperate D3D11 and D3D12 without using 11-on-12. You'll have to be careful to get the synchronization right, but it would look something like this:
> 
>     1. Receive a `Direct3D11CaptureFrame` from the capture API (keep a reference to it!).
> 
>     2. Extract the texture and QI for `IDXGIResource1`.
> 
>     3. Call [`IDXGIResource1::CreateSharedHandle`](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgiresource1-createsharedhandle) to obtain a handle to the texture.
> 
>     4. Call [`ID3D12Device::OpenSharedHandle`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-opensharedhandle) to open the texture with your D3D12 device.
> 
>     5. Do whatever you need to do on D3D12. I recommend making a copy to process later, this should be as short as possible.
> 
>     6. Signal a fence created on that same D3D12 device and use something like [`ID3D12Fence::SetEventOnCompletion`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-seteventoncompletion) to be notified when that work has completed.
> 
>     7. Only when you're sure you're not using the ID3D12Resource anymore on the GPU, release all of the references to the texture and then finally call `Close` on your `Direct3D11CaptureFrame` from step 1.
> 
> 
> You'll need to profile your implementation, but I would expect it to be faster than copying the bytes to system memory and then back to video memory.

One last question about that chain you just wrote. Let's say I want to take that capture from WGC (or a captured texture from Desktop Duplication) that was taken on another adapter and then encode it with Media Foundation, which uses the default adapter. Could I:

1) Create a shared resource on the dedicated GPU adapter
2) Create a shared resource on the integrated GPU adapter
2) Capture the desktop duplication frame and copy it to the dedicated GPU shared resource
3) Create a D3D12 device on the integrated GPU and open the dedicated GPU shared resource
4) Copy it to integrated GPU shared resource
5) Then encode the shared integrated GPU resource with Media Foundation

**Comment by robmikh** [comment]
I think the important part would be to make sure you're calling [`IDXGIOutputDuplication::ReleaseFrame`](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-releaseframe) _after_ you know the copy involving the DDA frame has executed on the GPU (hence the fence). Although it's been awhile since I've looked at the DDA code so I'm less familiar with how it does synchronization.

As for copying between the two adapters, I'm less familiar with how that's supposed to work on D3D12. You'll probably want to find a more definitive source on that one. The DirectX folks now have a [Discord channel](https://devblogs.microsoft.com/directx/hello-discord/) where they or someone in the community could give you better advice on that part.

**Comment by robmikh** [comment]
I'm going to close this issue for now, I just want to point you towards a sample I dug up first:

https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HeterogeneousMultiadapter

**Comment by robmikh** [comment]
Ah, interesting! Thanks for the follow up, I didn't know that about D3D12 cross-adapter! I'd still be interested in what the performance difference between D3D12 and a naive D3D11 cross-adapter test would be... I might have to dig into it some day 🙂 

Thanks again for circling back on this, I appreciate it!
