### ISSUE TITLE
Windows graphics capture vs DDA?

### ISSUE THREAD

**Issue by M-U-X** [robmikh/Win32CaptureSample#48]
This is more of a question because I don't have somewhere else to ask, and the info about WindowsGraphicsCapture underlying technology seems scarce, what are the advantages & drawbacks of using either over the other, especially performance wise, also can Windows  GraphicsCapture be used with hardware encoders like Nvenc and so on the same way DDA can be used, finally is there a difference between their D3d11 & 12 support rn for FSE games?

**Comment by robmikh** [comment]
At the end of the day, both WGC and DDA are drawn by the system compositor* (DWM). So they should have similar performance, their main difference comes from their exposed capabilities. 

Here are some advantages of WGC over DDA:

- You can capture individual windows, as well monitors.
- You can capture arbitrary visual trees you own (Windows.UI.Composition).
- Callable from a UWP app. Both WGC and DDA are callable from Win32 apps.

With that said, we're still adding features and working on WGC so it doesn't have all of DDA's features yet. Namely:

- DDA can capture the secure desktop (UAC prompts) if started from the SYSTEM account.
- Dirty region reporting.
- Callable from a non-interactive user context.
- Can capture truly full screen exclusive games (both can capture EFSE games).

Both WGC and DDA provide textures back in video memory (assuming you aren't using a WARP device 🙂), and can be provided to hardware encoders. I've used it personally with Windows.Media.Transcoding as well as Media Foundation to encode H.264 video.

* - Both are drawn by the DWM, but DDA is also able to get the contents of the screen if it's owned by another application (e.g. truly full screen games).

**Comment by M-U-X** [comment]
Wow I didn't expect such a fast reply, tysm, and sorry, if this is a bother I'll stop asking question, but if not, I got a couple more since (sorry if they seem dumb XD) you seem quite knowledgeable on this and stackoverflow is quite hostile XD, would using "Windows.Media.Transcoding, Media Foundation & so on" offer any advantage (whether performance wise or otherwise) over directly using NVenc/AMD AMF/intel Quicksync APIs, are there any plans for porting WGC to older versions of windows? and an interesting thing, if you have explorer.exe process completely killed "taskkill /F /IM explorer.exe" WPF apps won't be able to start, & when I try to run the official WGC Win32 code capture sample "Windows.UI.Composition-Win32-Samples-master\cpp\ScreenCaptureforHWND" it results in an exception, so I imagine for WGC to work explorer.exe (shell) should be running, or is there a way around that?, what about D3D11, 12 are both APIs capable of capturing games running either, finally https://obsproject.com/forum/threads/windows-graphics-capture-vs-dxgi-desktop-duplication.149320/ here it says "The main benefit of WGC capture is that it works cross-GPU with no user intervention. DXGI requires OBS to run on the same GPU as the display." what exactly does this mean, say if it's capturing a game running on a GPU, while it's running on another (for example in a switchable graphics systems) it'll transfer or allow you to transfer the frames to the other GPU or what exactly, I'm sorry if any of the questions seemed too dumb, but I can't really find much technical details on WGC on msdn

**Comment by robmikh** [comment]
The main advantage of using the system provided encoding APIs is that it provides an abstraction that any encoder can plug into. If you use vendor specific APIs, you have to make sure the right hardware is present and you must code specifically to each one. If you're doing something mainstream (e.g. H.264), the system APIs are a good start. If you have very specific needs, or if the encoder you wish to use isn't exposed through Media Foundation, I'd use the vendor specific APIs.

As for explorer.exe and WGC, yes explorer.exe needs to be running. Under the covers, WGC is really a mechanism to draw visual trees. In order to draw a window or a monitor, we talk to the shell which will point us to the correct root visual to draw. This dance requires explorer.exe to be running/healthy.

As for graphics technologies: It doesn't matter what graphics technology the application is using, WGC can still capture it. The app can use GDI, DirectX, OpenGL, Vulkan, etc. Keep in mind, the rules about full screen exclusive mode still applies. For example, OpenGL and Vulkan games do not participate in the emulated full screen exclusive mode, and thus the DWM does not have access to their contents when full screen.

When it comes to multi-adapter systems, yes, WGC will allow you to capture using a different adapter than what's used by the application being captured. However, there is a performance penalty for this, as the system compositor cannot copy from one adapter's video memory to another. To do the cross-adapter copy, we first copy the bytes to system memory and then back into the video memory of the target adapter. DDA is unable to do this, as the API is expressed through the adapter (Adapter -> Output -> OutputDuplication). There are other issues in this repo which have discussed cross-adapter scenarios with WGC (e.g. #46).

And finally, your scenario involving a system with both an iGPU and dGPU: That really comes down to just how squeezed the game is for GPU resources and the overhead of the encoding operation vs copying the bytes to system memory. But I wouldn't expect it to be worth it from a performance perspective, unless your encoder is (heavily) using the 3d engine on your card as well as the media engines. But this is where we're veering away from any expertise I may have 🙂.

I'm going to close this issue, but if you have more questions about Windows.Graphics.Capture, feel free to open a new issue. You may get better answers on other topics on other forums/communities.
