### ISSUE TITLE
Why did I get black image (all pixel is 0x00)?

### ISSUE THREAD

**Issue by SheenArtem** [robmikh/Win32CaptureSample#52]
Dear Robbert,

Thanks for these sample code.

Here is my dll project:
[https://github.com/SheenArtem/WinRT_WndCapture](https://github.com/SheenArtem/WinRT_WndCapture)

I'm trying to make a window capture and access the pixel of the captured frame.

`m_swapChain->Present1(1, 0, &presentParameters);` works fine and displays correct image of the target window.

But the pixel data that I want to access are always 0x00.

So I get a black image at all time.

(I used the memory debug window to watch the memory location of `source`)

In the SimpleCapture.cpp, I added some code in OnFrameArrived() :
`            D3D11_TEXTURE2D_DESC desc;`
`            surfaceTexture->GetDesc(&desc);`
`            com_ptr<ID3D11Texture2D> CopyBuffer = CreateStageTexture2D(d3dDevice,`
`                static_cast<uint32_t>(desc.Width),`
`                static_cast<uint32_t>(desc.Height),`
`                static_cast<DXGI_FORMAT>(DirectXPixelFormat::B8G8R8A8UIntNormalized));`

`            m_d3dContext->CopyResource(CopyBuffer.get(), surfaceTexture.get());`

`            D3D11_MAPPED_SUBRESOURCE mapped = {};`
`            winrt::check_hresult(m_d3dContext->Map(CopyBuffer.get(), 0, D3D11_MAP_READ, 0, &mapped));`
`            std::vector<byte> bits(desc.Width * desc.Height * 4, 0);`
`            auto dest = bits.data();`
`            auto source = reinterpret_cast<byte*>(mapped.pData);`
`            for (auto i = 0; i < (int)desc.Height; i++)`
`            {`
`                memcpy(dest, source, desc.Width * 4);`
`                source += mapped.RowPitch;`
`                dest += desc.Width * 4;`
`            }`
`            m_d3dContext->Unmap(CopyBuffer.get(), 0);`

And here's my method to create staging texture

`inline auto`
`CreateTexture2D(`
`    winrt::com_ptr<ID3D11Device> const& device,`
`    const D3D11_TEXTURE2D_DESC* desc)`
`{`
`    winrt::com_ptr<ID3D11Texture2D> texture;`
`    winrt::check_hresult(device->CreateTexture2D(desc, nullptr, texture.put()));`
`    return texture;`
`}`

`inline auto`
`CreateStageTexture2D(`
`    winrt::com_ptr<ID3D11Device> const& device,`
`    uint32_t width,`
`    uint32_t height,`
`    DXGI_FORMAT format)`
`{`
`    D3D11_TEXTURE2D_DESC DeskTexD = {};`
`    DeskTexD.Width = width;`
`    DeskTexD.Height = height;`
`    DeskTexD.Format = format;`
`    DeskTexD.MipLevels = 1;`
`    DeskTexD.ArraySize = 1;`
`    DeskTexD.SampleDesc.Count = 1;`
`    DeskTexD.SampleDesc.Quality = 0;`
`    DeskTexD.Usage = D3D11_USAGE_STAGING;`
`    DeskTexD.BindFlags = 0;`
`    DeskTexD.CPUAccessFlags = D3D11_CPU_ACCESS_READ;`
`    DeskTexD.MiscFlags = 0;`
`    return CreateTexture2D(device, &DeskTexD);`
`}`

Did I miss some steps ?

Thanks again for the help.

**Comment by robmikh** [comment]
Unfortunately, I'm not sure. I'm unable to repro the issue. When I run the program using the UI, I can see the correct bytes in the `source` variable. If you tried to access the data using the exported functions, the `rawdata` static variable won't have anything in it unless you're pumping messages. That's because the frame pool is being created with `Create`, which uses the `DispatcherQueue` to run the `FrameArrived` callback on the thread that created the frame pool. If you use `CreateFreeThreaded`, the `FrameArrived` callback will be called on the capture thread. However you'll need to figure out the synchronization between threads and how to create that interface with your caller.

This project's README has a little more information on the `Create` vs `CreateFreeThreaded` topic.
