### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by daneden21** [robmikh/Win32CaptureSample#78]
Hi,

I just wanted to thank you for this nice piece of code. I used it to learn c++ and to get into screen capturing. Its not over complex and a good example how to code. The winrt composition is a real performance break so I used dcomp instead.

Keep on coding;

Kind regards

Daniel

**Comment by robmikh** [comment]
Thanks for the kind words! I'm glad you've found the sample useful.

A quick note on WUC performance vs dcomp, there really shouldn't be a difference. What's likely the cause here is that the sample uses a stretch mode on the brush, which is something that is new to WUC. If you were to set the stretch mode to None it would behave like dcomp.
