### ISSUE TITLE
Question: why WGC can not capture csgo on some computers

### ISSUE THREAD

**Issue by MemeTao** [robmikh/Win32CaptureSample#84]
For some games, such as Rainbow Six and CSGO, WGC(window capture) cannot capture it when the game enters full screen mode.

**Comment by robmikh** [comment]
This has to do with what rendering back end CSGO is using and whether it is running in true full screen mode.

Games that enter full screen mode (i.e. the game owns the monitor, not a borderless window, not emulated full screen) are not capturable by Windows.Graphics.Capture since the DWM cannot see those pixels. You'll need to use DDA for that.

Usually when the game is set to full screen and the rendering back end is set to Vulkan, you can get this behavior. Usually D3D games are set to use emulated full screen by the OS.
